# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20170117_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='state',
            field=models.IntegerField(choices=[(0, 'Unstarted'), (1, 'Started'), (2, 'Finished')], default=0),
            preserve_default=False,
        ),
    ]
