# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_milestone_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='state',
            field=models.IntegerField(choices=[(0, 'Unstarted'), (1, 'Started'), (2, 'Finished')], default=0),
        ),
        migrations.AlterField(
            model_name='progress',
            name='code_name',
            field=models.SlugField(default='', unique=True),
        ),
    ]
