# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20170124_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
