# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_suggest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suggest',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
