# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_auto_20170124_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
