# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_suggest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='google_image',
            field=models.URLField(blank=True),
        ),
    ]
