# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 16:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_suggest_google_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='google_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=[], size=None),
        ),
    ]
