# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0008_auto_20170125_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggest',
            old_name='chosen',
            new_name='is_chosen',
        ),
    ]
