# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0009_auto_20170130_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
