# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0010_suggest_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='suggest',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
