"""
Django settings for root project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

import environ
from celery.schedules import crontab
from django.core.urlresolvers import reverse_lazy

env = environ.Env(
    DEBUG=(bool, True),
    SECRET_KEY=(str, '#3pw2ogg-#q7r%abn2sy+zsaqnek2tp7g@ke+za46)#hb+pbka'),
    ALLOWED_HOSTS=(str, ''),
    DATABASE_URL=(str, 'sqlite:///sqlite.db'),
    EMAIL_URL=(str, ''),
    DEFAULT_FROM_EMAIL=(str, 'admin@domain.com'),
    HEADER_POST_ID=(int, 1),
    HEADER_PROGRESS_ID=(int, 1),
    POST_PER_PAGE=(int, 5),
    FACEBOOK_APP_ID=(str, ''),
    GCM_ID=(str, ''),
    GCM_KEY=(str, ''),
    GOOGLE_MAP_API_KEY=(str, ''),
    ROUTE_SUGGEST_LIST_PAGE_SIZE=(int, 4),
    CACHE_URL=(str, 'rediscache://127.0.0.1:6379:1'),
    REDIS_URL=(str, 'redis://127.0.0.1:6379/0'),
    REST_FRAMEWORK_THROTTLE_ROUTE_SUGGEST=(str, '20/day'),
    FACEBOOK_ACCESS_TOKEN=(str, ''),
    FACEBOOK_GRAPH_VERSION=(str, 'v2.8'),
)
ENV = env  # so it will be copied to django.conf.settings
env.read_env('.env')

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
root = environ.Path(__file__) - 3
BASE_DIR = root()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')
ALLOWED_HOSTS = ALLOWED_HOSTS.split(',') if ALLOWED_HOSTS else []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # The Django sites framework is required
    'django.contrib.sites',

    'django_extensions',
    'djcelery_email',
    'ckeditor',
    'ckeditor_uploader',
    'webpush',
    'rest_framework_swagger',

    'accounts',
    'common',
    'progress',
    'blog',
    'route',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'root.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'common.context_processors.site_name',
                'common.context_processors.django_settings',
                'common.context_processors.nav_links',
            ],
        },
    },
]

WSGI_APPLICATION = 'root.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': env.db()
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = 'static'
STATIC_URL = '/static/'

MEDIA_ROOT = 'media'
MEDIA_URL = '/media/'

AUTH_USER_MODEL = 'accounts.User'

SITE_NAME = os.getenv('SITE_NAME', 'Django')
SITE_ID = 1

TEST_RUNNER = 'common.tests.core.DjangoNoseTestSuiteRunner'

LOGIN_URL = reverse_lazy('admin:login')
LOGOUT_URL = reverse_lazy('admin:logout')
LOGIN_ERROR_URL = reverse_lazy('index')
LOGIN_REDIRECT_URL = reverse_lazy('index')

CACHES = {
    'default': env.cache(),
 }

vars().update(env.email(backend='djcelery_email.backends.CeleryEmailBackend'))
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_REQUIRED = True

# CKEDITOR https://github.com/django-ckeditor/django-ckeditor
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'],
            ['Find', 'Replace', '-', 'SelectAll', '-', 'Scayt'],
            ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
             'HiddenField'],
            '/',
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
             'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
             'Language'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe'],
            '/',
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks'],
        ]
    }
}

# WEBPUSH CONFIG https://github.com/safwanrahman/django-webpush
WEBPUSH_SETTINGS = {
    'GCM_ID': env('GCM_ID'),
    'GCM_KEY': env('GCM_KEY'),
}

# WEBSITE CONFIG
HEADER_POST_ID = env('HEADER_POST_ID')
HEADER_PROGRESS_ID = env('HEADER_PROGRESS_ID')
POST_PER_PAGE = env('POST_PER_PAGE')
FACEBOOK_APP_ID = env('FACEBOOK_APP_ID')
ROUTE_SUGGEST_LIST_PAGE_SIZE = env('ROUTE_SUGGEST_LIST_PAGE_SIZE')
FACEBOOK_ACCESS_TOKEN = env('FACEBOOK_ACCESS_TOKEN')
FACEBOOK_GRAPH_VERSION = env('FACEBOOK_GRAPH_VERSION')

# route config
GOOGLE_MAP_API_KEY = env('GOOGLE_MAP_API_KEY')

# REST FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'route_suggest': env('REST_FRAMEWORK_THROTTLE_ROUTE_SUGGEST'),
    }
}


# REDIS https://redis-py.readthedocs.io/en/latest/#redis.StrictRedis.from_url
REDIS_URL = env('REDIS_URL')

# CELERY CONFIG http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#crontab-schedules
CELERYBEAT_SCHEDULE = {
    'update-suggest-like': {
        'task': 'route.tasks.update_suggest_count',
        'schedule': crontab()
    }
}
